version: "3.7"
services:
    app:
        build:
            args:
                user: local
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: brandlist
        container_name: brandlist-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        #command: sh -c "composer install --ignore-platform-reqs && php artisan key:generate && php artisan migrate"
        networks:
            - brandlist
    db:
        image: mysql:8.0
        container_name: brandlist-db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - brandlist
    nginx:
        image: nginx:alpine
        container_name: brandlist-server
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - brandlist
networks:
    brandlist:
        driver: bridge
